tasker_task:
    resource: "@TaskerBundle/Resources/config/routing/task.yml"
    prefix:   /task

tasker_homepage:
    path:     /
    defaults: { _controller: TaskerBundle:Default:index }

tasker_board:
    resource: "@TaskerBundle/Resources/config/routing/board.yml"
    prefix:   /board